--- 
phases: 
  build: 
    commands: 
      - "echo Build started on `date`"
      - "echo Building the Docker image..."
      - "docker build -t iltonjunix/projecttest ."
      - "docker tag iltonjunix/projecttest iltonjunix/projecttest:latest"
  post_build: 
    commands: 
      - "echo Build completed on `date`"
      - "echo Pushing the Docker image..."
      - "docker push iltonjunix/projecttest:latest"
  pre_build: 
    commands: 
      - "echo Logging in to Docker Hub..."
      - "docker login --username=\"iltonjunix\" --password=\"966635dd-3a3b-4bbb-b288-d8af493cb7c2\""
version: 0.1
